# Generated by Django 5.0.6 on 2024-06-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUHP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docsave',
            name='file_doc',
            field=models.ImageField(null=True, upload_to='static/images/demo'),
        ),
        migrations.AlterField(
            model_name='reportsave',
            name='file_rep',
            field=models.FileField(null=True, upload_to='static/report/pdf'),
        ),
        migrations.AlterField(
            model_name='reportsave',
            name='img_cp_rep',
            field=models.ImageField(null=True, upload_to='static/report/imgs'),
        ),
    ]
